fix: date check, -d and -g can't be used together

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -26,7 +26,6 @@ print_help() {
 }
 
 error() {
-    echo >&2 "error"
     exit 1
 }
 
@@ -114,7 +113,6 @@ if [ "$1" == "list" ] || [ "$1" == "secret-log" ]; then
     shift
 fi
 
-
 while getopts "g:a:b:mhd" args; do
     case "${args}" in
     h)
@@ -124,6 +122,7 @@ while getopts "g:a:b:mhd" args; do
     g)
         GROUP=${OPTARG}
         FILE=${OPTARG}
+        [ "$IGNORE" = true ] || { echo >&2 "-g and -d can't be defiend together"; error; }
         ;;
     m)
         DIRECTORY=${OPTARG}
@@ -139,20 +138,15 @@ while getopts "g:a:b:mhd" args; do
         ;;
     a)
         DATE_AFTER=${OPTARG}
-        if [[ ! "$DATE_AFTER" =~ ^[0-9]{4}-[0-1][0-9]-[0-3][0-9]$ ]]; then
-            echo >&2 "Date $DATE_AFTER is not in YYYY-MM-DD format"
-            exit 1
-        fi
+        date -d "$DATE_AFTER" > /dev/null 2>&1 || { echo >&2 "Date $DATE_AFTER is not in YYYY-MM-DD format"; exit 1; }
         ;;
     b)
         DATE_BEFORE=${OPTARG}
-        if [[ ! "$DATE_BEFORE" =~ ^[0-9]{4}-[0-1][0-9]-[0-3][0-9]$ ]]; then
-            echo >&2 "Date $DATE_BEFORE is not in YYYY-MM-DD format"
-            exit 1
-        fi
+        date -d "$DATE_BEFORE" > /dev/null 2>&1 || { echo >&2 "Date $DATE_BEFORE is not in YYYY-MM-DD format"; exit 1; }
         ;;
     d)
         IGNORE=true
+        [ -z "$GROUP" ] || error "-g and -d can't be defiend together"
         ;;
     *)
         FILE=$1
