fix,feat: directory filter,  filter by group

diff --git a/mole b/mole
--- a/mole
+++ b/mole
@@ -7,9 +7,9 @@ export POSIXLY_CORRECT=yes
 export LC_NUMERIC=en_US.UTF-8
 
 print_help() {
-    echo " " 
+    echo " "
     eval ./cat.sh
-    echo " " 
+    echo " "
     echo "Usage: "
     echo "      mole [-h]"
     echo "      mole [FILTERS] [DIRECTORY]"
@@ -27,9 +27,9 @@ print_help() {
 
 check() {
     if [ $(wc -c) -gt "0" ]; then
-        echo "error: no files found!" >> /dev/stderr
+        echo "error: no files found!" >>/dev/stderr
         exit 1
-    fi 
+    fi
 }
 
 open() {
@@ -80,11 +80,15 @@ ignore() {
     fi
 }
 
+group() {
+    awk -F '|' -v group="$GROUP" '{if ($2 = group || length(group) == 0) print}'
+}
+
 directory() {
     cat $MOLE_RC | awk -v dir=$FILE 'BEGIN{FS="|"} { 
-            n = split($4,a,"/"); 
-            if (a[n-1] == dir) print $0; 
-        }' | sed -r "s:${FILE}/::g"
+        n = split($4,a,"/"); 
+        if (a[n-1] == dir || length(dir) == 0) print;
+    }' | sed -r "s:${FILE}/::g"
 }
 
 DATE=$(date +%F_%H-%M-%S)
@@ -92,31 +96,34 @@ DATE_AFTER="0000-00-00"
 DATE_BEFORE="9999-99-99"
 FILE=""
 GROUP="-"
-FILTER=""
+FILTER=""s
 DIRECTORY=""
 COMMAND=""
 IGNORE=false
 
 # check if utillity realpath is available
 if ! [ -x "$(command -v realpath)" ]; then
-    echo "<realpath> could not be found" >> /dev/stderr
+    echo "<realpath> could not be found" >>/dev/stderr
     exit 1
 fi
 
 # look for MOLE_RC, export MOLE_RC=$HOME/.config/molerc
 if [ -n "$MOLE_RC" ]; then
     if [ ! -e "$MOLE_RC" ]; then
-        touch "$MOLE_RC"
+        touch "${MOLE_RC}"
     fi
 else
-    echo "MOLE_RC can't be found" >> /dev/stderr
+    echo "MOLE_RC can't be found" >>/dev/stderr
     exit 1
 fi
 
- # Ak je mole spustený bez argumentov, vyberie súbor ktorý bol pomocou skriptu editovaný ako posledný
-if [ $# = 0 ]; then 
+# Ak je mole spustený bez argumentov, vyberie súbor ktorý bol pomocou skriptu editovaný ako posledný
+if [ $# = 0 ]; then
     FILE=$(cat "$MOLE_RC" | awk 'BEGIN{FS="|"} END{print $1}') # uniq -c | sort -bgr |
-    [ -e "$FILE" ] || { echo "error: no file!"; exit 1; }
+    [ -e "$FILE" ] || {
+        echo "error: no file!"
+        exit 1
+    }
     open
 fi
 
@@ -135,11 +142,15 @@ while [ "$#" -gt 0 ]; do
         FILTERS+=$1
         GROUP=$2
         FILE=$3
+        if [ -n "$FILE" ]; then
+            shift
+        else
+            FILE=""
+        fi
         [ "$IGNORE" = false ] || {
-            echo "error: -g and -d can't be used together" >> /dev/stderr
+            echo "error: -g and -d can't be used together" >>/dev/stderr
             exit 1
         }
-        shift
         shift
         shift
         ;;
@@ -162,7 +173,7 @@ while [ "$#" -gt 0 ]; do
         FILTERS+=$1
         DATE_AFTER=$2
         date -d "$DATE_AFTER" >/dev/null 2>&1 || {
-            echo "error: Date $DATE_AFTER is not in YYYY-MM-DD format" >> /dev/stderr
+            echo "error: Date $DATE_AFTER is not in YYYY-MM-DD format" >>/dev/stderr
             exit 1
         }
         shift
@@ -172,7 +183,7 @@ while [ "$#" -gt 0 ]; do
         FILTERS+=$1
         DATE_BEFORE=$2
         date -d "$DATE_BEFORE" >/dev/null 2>&1 || {
-            echo "error: Date $DATE_BEFORE is not in YYYY-MM-DD format" >> /dev/stderr
+            echo "error: Date $DATE_BEFORE is not in YYYY-MM-DD format" >>/dev/stderr
             exit 1
         }
         shift
@@ -182,13 +193,13 @@ while [ "$#" -gt 0 ]; do
         FILTERS+=$1
         IGNORE=true
         [ -z "$GROUP" ] || {
-            echo "error: -g and -d can't be used together" >> /dev/stderr
+            echo "error: -g and -d can't be used together" >>/dev/stderr
             exit 1
         }
         shift
         ;;
-    -?)        
-        echo "error: Unknown argumetns!" >> /dev/stderr
+    -?)
+        echo "error: Unknown argumetns!" >>/dev/stderr
         exit 1
         ;;
     *)
@@ -203,7 +214,7 @@ done
 case "$COMMAND" in
 list)
     IGNORE=false
-    cat "$MOLE_RC" | directory | date_before | date_after | awk -F "|" '{print $1": "$2}' | sort -u | \
+    cat "$MOLE_RC" | group | date_before | date_after | directory | awk -F "|" '{print $1": "$2}' | sort -u |
         awk 'BEGIN{FS=" "} {
             if (length(arr[$1]) == 0) 
                 arr[$1] = $2;
@@ -225,19 +236,20 @@ secret-log)
         } END{ 
             for (i in arr)
                 printf i";"arr[i]"\n"
-         }' | sort | bzip2 -c > /home/"$USER"/.mole/log_"$USER""_""$DATE".bz2
+         }' | sort | bzip2 -c >/home/"$USER"/.mole/log_"$USER""_""$DATE".bz2
     exit 0
     ;;
 *)
-    if [ -z "$FILE" ]; then 
+    if [ -z "$FILE" ]; then
         # ak na vstupe nieje zadany subor, vyhladaj posledny editovany
         FILE=$(cat $MOLE_RC | awk -v file=$FILE 'BEGIN{FS="|"} {
             if (length(file) == 0) print;
             else if ( $1 ~ file) print;
         } ' | most | awk -F "|" '{print $1}')
     fi
-    open 
+    open
+    ;;
 esac
 
-echo "error: Unknown argumetns!" >> /dev/stderr
+echo "error: Unknown argumetns!" >>/dev/stderr
 exit 1
